### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/Car-Acceptability-Prediction#15]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work! 

Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

- [ ] Challenging question- Tests arent present for any of the scripts. -7 
- [ ] data_processing.py script is missing author name. Add that. 
- [ ] Some of the dependencies versions are not mentioned -0.5
- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). -0.5 writing
**Comment:** Although the yaml file is present, creating and activating the required conda environment is missing. For example the two commands you would add to your readme before starting with data download would be- ```conda env create -f env522car.yaml``` and ```conda activate 522env```. Additionally you will also add a command for cloning your repository before everything.
- [ ] The proposal.md file has been created and moved to the doc directory -2 mechanics
**Comment:** proposal.md file is missing from the doc directory. 
- [ ] There are not figure captions. -0.5 viz
**Comment:** The final rendered version of the report is missing figure captions. It is present within the rmd but doesnt get rendered properly.
