### ISSUE TITLE
Summary of feedback received during Milestone 3

### ISSUE THREAD

**Issue by pengzh313** [UBC-MDS/Car-Acceptability-Prediction#19]
Every feedback is important for us to improve our project. We appreciate the instructor, TAs and peer reviewers' time to provide these valuable feedback.

Below we put together comments from reviewers to start with our project improvement. Similar comments have been filtered to only list one here.

**Team Members**: **Please read through below comments, and add your notes if there are modifications you have already made regarding the particular comments listed here. The purpose is to keep us on the same page and team members can work on the further improvement efficiently**.

### TA comments:

Check the <a href="https://github.com/UBC-MDS/Car-Acceptability-Prediction/issues/15" target="_blank">link_1</a> and [link_2](https://github.com/UBC-MDS/Car-Acceptability-Prediction/issues/18) to the original comments for details if needed.

#### Makefile

-   [x] Target for all can be simplified to doc/car_popularity_prediction_report.html and doc/car_popularity_prediction_report.md only as the other files are needed to generate the report. [[link to commit] ](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/8bab67906a12154ab475304b7a13ded9a120b756)

#### Scrips & Usage & ReadMe

-   [ ] Challenging question- Tests aren't present for any of the scripts\
    Notes: (**Add your notes here if any**)

-   [x] Data_processing.py script is missing author name.\
    Notes: Author names have been added. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/c24b3a81a02f2931356e16690f8a5be7bb67f463)

-   [x] Some of the dependencies versions are not mentioned\
    Notes: All Python dependencies versions have been added. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/6b01622ab34d127ab190e1b35fab7cbb9490cf04). 
    R dependencies have been added. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/43154f57b5033eeacfea0e3e2e0f70bec6679b4d).

-   [x] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing).
     In the usage for cloning the repository, make sure to include the actual URL link and current tag so that users can directly copy and paste it (git clone {repo URL})
    Notes: [[link to commit]](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/a12f0033435ec2b36efcb3d1817729bd76ef80a4)
- [x] Missing libraries used in the Rscript (ie pandoc). Make sure to rerun the whole project from scratch in a whole new environment.   
    Notes: pandoc library has been added in car_popularity_prediction_report.Rmd. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/7188950d37b1aebd7029a61fb54a49bab8ac9023)

#### Documentation

-   [x] proposal.md file is missing from the doc directory\
    Notes: Proposal.md file has been added in the doc directory. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/eb252e06197e7e5a4035fc7e04c27784ba5cd928)

-   [x] The final rendered version of the report is missing figure captions. It is present within the rmd but doesnt get rendered properly\
    Notes: Updated Rscript in ReadMe to render as default. Now figure captions showing properly in the output html file. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/3f4404415604ac2e602145e629486ebc0a2472f8)

#### GItHub release

-   [ ] Please provide the link to the release as https://github.com/UBC-MDS/REPOSITORY/tree/VERSION (replacing REPOSITORY and VERSION with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history.    
    Notes:

### Peer Review comments:

Check the <a href="https://github.com/UBC-MDS/data-analysis-review-2022/issues/6" target="_blank">link</a> to the original comments for details if needed.

#### Scrips & Usage & ReadMe

-   [x] A very minor suggestion for reproducibility would be to include the code for creating and activating the conda environment in the Usage section as well
    Notes: [[link to commit]](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/6b01622ab34d127ab190e1b35fab7cbb9490cf04)

-   [x] You repeat yourself in this part of your README\
    Notes: Updated. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/ab65e50338d97c8845c4f6c6e82ae9327aab9893)

-   [ ] For Table 1, adding a column specifying which model each of the rows is associated with would greatly improve its readability. For Table 2, perhaps make the column headers more "human-readable" and round to 3 significant digits where needed. I also agree with the reviewer above about adding some Figure captions, and also try and center the figures in the report to improve its organization/readability.\
    Notes:

-   [x] Some of the EDA figures in the Results & Discussion section of the report could be developed further to adhere to proper data visualization guidelines and improve their readability. For example, Figure 1 could be rotated so that the longer variable names are show horizontally, instead of vertically, making them easier to read. Additionally, while it isn't a big issue, editing the axis labels in Figures 1 and 2 to add capitalization and remove underscores from variable names would make the figures more presentable. The addition of figure captions would be useful as well for future readers\
    Notes: Updated figure 1 to display horizontally instead of vertically. [[link to commit]](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/8548b94c696fd727a7fb5a98f388eeed093aeac0)

#### Documentation

-   [x] This checklist asks for author affiliations in the final report, so perhaps include those. Also, please check over the grammar in the report, as there are some small errors throughout (run-on sentences, "public available dataset" instead of "publicly available dataset", changing from past tense to present tense and then back to past tense in the same paragraph, etc).\
    Notes: Updated in the report. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/e50be161f8b5dfa84f466f6adcbe39ae87b15c55)

-   [x] Perhaps keep references out of the body of the report (i.e. "which is presented in B. Zupan, M. Bohanec, I. Bratko, J. Demsar: Machine learning by function decomposition. ICML-97, Nashville, TN. 1997.") and refer to it with an in-text citation while moving the full citation to the References section instead.\
    Notes: This was referring to the Reference 3 (1997) Car Evaluation in the report. 

-   [x] This line of your report doesn't flow very well and I would consider rewording it\
    Notes: Updated in the report. [link to commit](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/e50be161f8b5dfa84f466f6adcbe39ae87b15c55)

-   [x] Upon reading your Team Code of Conduct it appears that some sections may have been meant to be formatted as a bullet point list; however, the different points all appear as one long sentence/paragraph (see below for an example), which hinders the readability of the code of conduct\
    Notes: [[link to commit]](https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/2f63b4f081923f044cd27fe3858ef79e1db50821)

**Comment by LisaSeq** [comment]
@pengzh313 Since we added pandoc library in the rmd script. We also need to update the environment dependencies (YAML file) for it.

**Comment by pengzh313** [comment]
> @pengzh313 Since we added pandoc library in the rmd script. We also need to update the environment dependencies (YAML file) for it.

@LisaSeq Not only pandoc, I was thinking about our YAML and dependencies listed on ReadMe are for Python env. We may need to include R env for this project also, such as R version x.x.x and R packages and specific versions (knitr, tidyverse, kableExtra, etc.). I will look into this tomorrow.

**Comment by pengzh313** [comment]
> > @pengzh313 Since we added pandoc library in the rmd script. We also need to update the environment dependencies (YAML file) for it.
> 
> @LisaSeq Not only pandoc, I was thinking about our YAML and dependencies listed on ReadMe are for Python env. We may need to include R env for this project also, such as R version x.x.x and R packages and specific versions (knitr, tidyverse, kableExtra, etc.). I will look into this tomorrow.

@LisaSeq , I have added R dependencies in ReadMe. Since Conda is not good installing R packages, I did not modify the current YAML file (for Python only) in the repo. After consulting with the instructor, my understanding is that the env now is taken care by Dockerfile. So whoever wants to reproduce our project, they will install Python and R separately per our Dockerfile. (correct me if I am wrong)

**Comment by pengzh313** [comment]
@LisaSeq In addition, I have updated the comment within the peer review issue:
https://github.com/UBC-MDS/data-analysis-review-2022/issues/6
For other improvements not explicitly listed there, for grading purposes, TAs can always go to the Issue 19 (here) to check.
I am not quite sure if we can close all feedback due to the time constraint.

**Comment by LisaSeq** [comment]
@pengzh313 I agree with you. Thanks so much for commenting and clarifying the R environment dependencies. I did try a few times last night to update the YAML file with the R package with no success, so its good to know it is covered with the Docker file! I am good to proceed with what we have done so far.
