### ISSUE TITLE
Milestone 4 - Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/Car-Acceptability-Prediction#20]
**Congratulations** on finishing milestone 4! Below we list some specific feedback you can use to improve your project.

**Dependency diagram of the Makefile (max 5 points)**
-----
Satisfactory.

**Make your project reproducible (to the max) with Docker**
-----
**Dockerfile**
- [ ]  The dependencie versions are not pinned. -2 quality
- [ ]  The Dockefile could be simplified. For instance, multiple RUN instructions could be merged into one. -1 mechanics

**Analysis can be run reproducibly using documentation provided in the README**
Satisfactory.

**Final Submission: Improve the project based on the feedback received**
------
Satisfactory.

**Expectations**
------
- [ ] GitHub issues were not closed. -5 mechanics
